### ISSUE TITLE
unable to download brigthbox-cloud-controller-manager

### ISSUE THREAD

**Issue by tormath1** [brightbox/brightbox-cloud-controller-manager#92]
Hello,

I tried to deploy the Brightbox CCM using this: https://github.com/brightbox/brightbox-cloud-controller-manager/blob/master/config/cloud-controller.yml but I'm facing this issue:
```
Warning  Failed     10s (x2 over 27s)  kubelet            Failed to pull image "brightbox/brightbox-cloud-controller-manager:0.0.5": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/brightbox/brightbox-cloud-controller-manager:0.0.5": failed to resolve reference "docker.io/brightbox/brightbox-cloud-controller-manager:0.0.5": docker.io/brightbox/brightbox-cloud-controller-manager:0.0.5: not found
```

Any idea where is the image? `latest` does not work neither.

Thanks !

**Comment by andatche** [comment]
Hi Mathieu,

Brightbox CCM releases are now versioned in-step with k8s releases and it's strongly recommended to run the CCM version which matches your cluster version. For a full list of releases please see https://github.com/brightbox/brightbox-cloud-controller-manager/tags

Thanks for raising this, I'll update the example deployment manifests to include a note about versions.

Regards,
Ben
